server:
  port: 6060

spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  messages:
    basename: i18n/messages
    encoding: utf-8

  datasource:
    url: jdbc:postgresql://localhost:5432/hmartdb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

api:
  prefix: api/v1

jwt:
  expiration: 604800 # 7 days
  secret-key: ${JWT_SECRET_KEY:default-secret-key}

# AWS config (chỉ dùng nếu bạn upload file S3)
cloud:
  aws:
    access-key: ${AWS_ACCESS_KEY:your-access-key}
    secret-key: ${AWS_SECRET_KEY:your-secret-key}
    region: ${AWS_REGION:ap-southeast-1}
    bucket-name: ${AWS_BUCKET_NAME:tmart-bucket}

# Mail config (chỉ cần nếu bạn gửi email xác thực)
mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_USERNAME:your-email@gmail.com}
  password: ${MAIL_PASSWORD:your-password}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

link:
  frontend: http://localhost:6060/
 
